api:
  host: edge.ammp.io
  apiver: v0
data-endpoints:
  - name: default
    type: api
    config:
      host: edge.ammp.io
      apiver: v0
      timeout: 120
    isdefault: true
  - name: stage-mqtt
    type: mqtt
    config:
      host: mqtt.stage.ammp.io
      port: 8883